version: '2'
services:
  kong-database:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
        dev:
            aliases:
              - kong-database.127.0.0.1.xip.io
  kong:
    image: mashape/kong:0.8.0
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    links:
      - kong-database
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - DATABASE=postgres
    networks:
        dev:
            aliases:
              - kong.127.0.0.1.xip.io
  kongdashboard:
    image: pgbi/kong-dashboard:latest
    ports:
      - 3070:8080
    networks:
        dev:
            aliases:
              - kong-dashboard.127.0.0.1.xip.io
  kongfigure:
    build: ./kongfigure
    environment:
      - KONG_APP_NAME=kong-dashboard
      - KONG_HOST=kong.127.0.0.1.xip.io:8001
      - KONGDASHBOARD_VIRTUAL_HOST=kong-dashboard.127.0.0.1.xip.io
      - KONGDASHBOARD_HOST=kong-dashboard.127.0.0.1.xip.io
      - KONGDASHBOARD_PORT=8080
    links:
      - kongdashboard
    networks:
      - dev
networks:
  dev:
    driver: bridge
