version: "2"
services:
  memcached:
    image: memcached
    ports:
    - 11211
  api:
    build: ./app
    environment:
      - DEVELOPMENT=true
    ports:
      - 5000
    links:
      - memcached
  kongfigure:
    build: ./kongfigure
    environment:
      - KONG_APP_NAME=api1
      - KONG_HOST=kong.127.0.0.1.xip.io:8001
      - API_VIRTUAL_HOST=api1.127.0.0.1.xip.io
    links:
      - api
networks:
  dev:
    external:
      name: demo_dev
